name: Full Stack Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Image (Test)
        run: docker build -t backend-test ./backend

      - name: Run Backend Container (Test)
        run: docker run -d --name backend-test -p 8000:8000 backend-test

      - name: Wait for Backend to Start
        run: sleep 10

      - name: Run Django Migrations
        run: docker exec backend-test python manage.py migrate

      - name: Run Django Tests
        run: docker exec backend-test python manage.py test

      - name: Stop Test Container
        run: docker stop backend-test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Images (Compose)
        run: DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} docker compose build

      - name: Push Images (Compose)
        run: DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} docker compose push


  infrastructure-deploy:
    needs: build-test-push
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Wait for EC2 to initialize
        run: sleep 60

      - name: Get EC2 Public IP
        run: echo "EC2_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

      - name: Deploy Application on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}

            if [ ! -d "django-docker-ci-cd-pipeline" ]; then
              git clone https://github.com/Agnus-sk/django-docker-ci-cd-pipeline.git
            fi

            cd django-docker-ci-cd-pipeline
            git pull
            docker compose pull
            docker compose up -d
