name: Full Stack Django CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------------
      # Checkout Repository
      # ---------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ---------------------------------
      # Set up Docker
      # ---------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ---------------------------------
      # Build Backend for Testing
      # ---------------------------------
      - name: Build Backend Image (Test)
        run: docker build -t backend-test ./backend

      - name: Run Backend Container (Test)
        run: docker run -d --name backend-test -p 8000:8000 backend-test

      - name: Wait for Backend to Start
        run: sleep 10

      - name: Run Django Migrations
        run: docker exec backend-test python manage.py migrate

      - name: Run Django Tests
        run: docker exec backend-test python manage.py test

      - name: Stop Test Container
        run: docker stop backend-test

      # ---------------------------------
      # Login to Docker Hub
      # ---------------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ---------------------------------
      # Build All Images Using Compose
      # ---------------------------------
      - name: Build Images (Compose)
        run: DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} docker compose build

      # ---------------------------------
      # Push All Images Using Compose
      # ---------------------------------
      - name: Push Images (Compose)
        run: DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} docker compose push


      # ---------------------------------
      # Deploy to EC2 Automatically
      # ---------------------------------
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! -d "django-docker-ci-cd-pipeline" ]; then
              git clone https://github.com/Agnus-sk/django-docker-ci-cd-pipeline.git
            fi
            cd django-docker-ci-cd-pipeline
            git pull
            docker compose pull
            docker compose up -d

